{% set name = "pyaztro" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyaztro-{{ version }}.tar.gz
  sha256: 6eb114573ef75ada94b2f82394df8dcac392382ac6a99a6f97d515069a5b8560

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil
    - requests

test:
  imports:
    - pyaztro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sameerkumar18/pyaztro
  summary: A client library for aztro - The Astrology API
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
